tags:
  extraction:
    text:
      placedIn:
        startMarker: '<'
        endMarker: '>'
        terminationMarker: '/>'
        attributesNameValueSeparator: '='
        attributesValuesEnclosingMarker: '"'

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017